<main class="center-div">
    <div class="row">
        <div class="col-12">
            <ul class="lista">
                <li class="espacamento">
                    <a class="lista-dashboard" href="/">Home</a>
                </li>               
                <hr />
                <li class="espacamento">
                    <a class="lista-dashboard" href="dashboard/cadastraradministrador">Cadastrar administrador</a>
                </li>
                <hr />
                <li class="espacamento">
                    <a class="lista-dashboard" href="dashboard/listaradministradores">Listar administradores</a>
                </li>
                <hr />
                <li class="espacamento">
                    <a class="lista-dashboard" href="dashboard/cadastrarimovel">Cadastrar imóvel</a>
                </li>
                <hr />
                <li class="espacamento">
                    <a class="lista-dashboard" href="dashboard/listarimoveis">Listar imóveis</a>
                </li>               
                <hr />
                <li class="espacamento">
                    <a class="lista-dashboard" href="logout">Deslogar</a>
                </li>
                <hr />

            </ul>
        </div>
    </div>
</main>