<nav class="navbar navbar-light" style="background-color: #e6e6e6;">
    <a class="navbar-brand" href="#">
        <img src="nezuko-imoveis.png" width="160" height="60" alt="" loading="lazy" >
    </a>
    <?php
       session_start();
        if(!isset($_SESSION['id_usuario']) || $_SESSION['id_usuario'] == '' || !isset($_SESSION['nome']) || $_SESSION['nome'] == ''){
    ?>

    <a href="/login">
        <button type="button" class="btn btn-secondary">Login</button>
    </a>

    <?php } else { ?>
     <a href="/dashboard">
         <button type="button" class="btn btn-secondary">Dashboard</button>
     </a>
    <?php } ?>

</nav>
<main class="container-fluid">
    <br />
    <h1 class="centralizado">Ultimos imóveis cadastrados</h1>
    <div class="centralizado"><a class="btn btn-secondary"href="/todosimoveis">
       Todos os Imoveis
    </a>
    </div>
    <br />
    <div class="container">
    <div class="row">
    <?php foreach($this->view->imoveis as $id_imoveis => $imoveis){ ?>
        <div class="col-md-6 col-sm-12 mb-5">
            <a href=<?= "/imovel?id=" . $imoveis['id_imovel'] ?> class="list-group-item list-group-item-action">


                        <img class="card-img-top" src=<?= "/img/imoveis/" . $imoveis['imagem'] ?> width="100%" height="300" alt="" loading="lazy">
                        <div class="card-body">
                        <h2 class="centralizado"><?= $imoveis['titulo']?></h2>
                        <br />
                        <p class="centralizado"><?= $imoveis['descricao']?></p>
                        </div>
            </a>
                    </div>


    <?php } ?>
        </div>
    </div>
        <br />

</main>
<br />
<br />
<br />
<br />

<footer class="footer fixed-bottom" >
	<div class="container-fluid centralizado">
        <p>Nezuko Móveis sempre representando em WEB 1</p>
	</div>
</footer>
