</br></br>
<div class="container">
    <div class="centralizado"><a href="/" class="btn btn-primary mb-5">Home</a></div>
    <a href=<?="/imovel?id=".$this->view->imovel->id_imovel?> class="list-group-item list-group-item-action">
    <div class="row">
        <div class="col-8">
            <h2 class="centralizado"><?=$this->view->imovel->titulo?></h2>
            <p class="descricao-imovel">
                <?=$this->view->imovel->descricao?>
            </p>
        </div>
        <div class="col-4">
            <img src=<?="/img/imoveis/".$this->view->imovel->imagem?> width="100%" height="300" alt="" loading="lazy">
        </div>
    </div>
    </a>
</div>

<br />
