<div class="wrapper fadeInDown">
    <div class="formContent">
        <div class="">
            <h2 class="titulo-login">
                Faça Login no sistema
            </h2
        </div>
        <form method="post">
            <br />
            <input type="email" id="login" class="botao-login botao-login-texto" name="email" placeholder="Email">
            <br />
            <input type="password" id="password" class="botao-login botao-login-texto" name="senha" placeholder="Senha">
            <br />
            <input type="submit" class="botao-login" value="Log In">
        </form>
        <div class="formFooter">
            <a class="recuperar-senha" href="/recuperarSenha">Esqueceu a senha?</a>
        </div>
    </div>
</div>